### ISSUE TITLE
how to version/changelog etc

### ISSUE THREAD

**Issue by jfrer** [subugoe/tido#110]
In GitLab by @krvoigt on Oct 4, 2020, 21:50

Talk about how to do version/changelog etc - 

"As team we need to get guideline/rules to all act on the basis"

**Goals:**

* having consistent commit messages in order to automatize everything as far as possible
* we want to create the CHANGELOG automatically, e.g. by conventional-changelog

**Problems:**

* how to deal with merge commits? squashing locally?

**TODOs:**

* [x] @ghost creates a repository for playing around and exploring how commitizen works
  * cf. <https://gitlab.gwdg.de/subugoe/emo/committest>
* [x] @ghost looks into pre-commit hooks
* [x] @mweidling looks into checking commit messages via the CI/on server-side

**Comment by jfrer** [comment]
In GitLab by @mweidling on Oct 7, 2020, 12:04

A more extensive documentation of our meeting about this topic and decisions made can be found at https://intranet.sub.uni-goettingen.de/display/prjAhiqar/DevMeet%3A+Commit+messages+and+templates.

**Comment by jfrer** [comment]
In GitLab by @ghost on Oct 7, 2020, 12:07

thank you

**Comment by jfrer** [comment]
In GitLab by @ghost on Oct 8, 2020, 10:00

marked the checklist item **@ghost looks into pre-commit hooks** as completed

**Comment by jfrer** [comment]
In GitLab by @mweidling on Oct 9, 2020, 09:29

marked the checklist item **@mweidling looks into checking commit messages via the CI/on server-side** as completed

**Comment by jfrer** [comment]
In GitLab by @mweidling on Oct 9, 2020, 09:30

Instead of letting the CI check if commit messages comply the conventional commits, we could simply use Push Rules. These can be configured either on group level ("Push Rules" the navigation) or on repository level ("Settings" > "Repository" > "Push Rules").

**Comment by jfrer** [comment]
In GitLab by @mweidling on Oct 9, 2020, 15:48

unassigned @mweidling

**Comment by jfrer** [comment]
In GitLab by @ghost on Oct 28, 2020, 13:05

moved from subugoe/ahiqar/ahiqar#31

**Comment by jfrer** [comment]
In GitLab by @ghost on Nov 2, 2020, 11:33

I sketched a possible branching model for EMo (ignoring ahikar here as discussed in the planning).
I hope its somewhat self explanatory. https://gitlab.gwdg.de/subugoe/emo/Qviewer/-/wikis/Branching-Model

The changelog would be written by CI whenever there is a new release.

I have no clue about making the npm package, but maybe @mathias-goebel or @mweidling can add some comments on that.

@mathias-goebel / @mweidling / @ghost / @ghost What do you think?

**Comment by jfrer** [comment]
In GitLab by @ghost on Nov 2, 2020, 15:18

hehe, you are right, _except_ GitFlow is not a requirement anymore where devs have to extrapolate from what to do when.

**Comment by jfrer** [comment]
In GitLab by @ghost on Nov 2, 2020, 15:23

I documented what I did regarding the npm package creation some weeks ago here: https://intranet.sub.uni-goettingen.de/display/prjEMo/EMo+Developer+Documentation

**Comment by jfrer** [comment]
In GitLab by @ghost on Nov 2, 2020, 15:27

I remember, thank you. I tought about (wish for) something more automatically/streamlined - like whenever a release happens, a new npm package is released. Maybe this is already implemented but i wasn't bright enough to grasp it.

**Comment by jfrer** [comment]
In GitLab by @ghost on Nov 2, 2020, 15:35

yes, that would be great and that's the goal, but since I had / have no idea how to do it either, shouldn't we - first of all - provide a working package at least once manually? The steps I described are working as a general approach, but the contents I provided sadly didn't (cause it's the src code, not the build. Trying to release the build like it is in the artifact didn't work cause of a lacking package.json in the build dir.) I tried to get smarter according to the build openSeaDragon ships, but that sadly didn't help either

**Comment by jfrer** [comment]
In GitLab by @ghost on Nov 5, 2020, 14:52

unassigned @ghost

**Comment by jfrer** [comment]
In GitLab by @ghost on Nov 20, 2020, 07:13

https://intranet.sub.uni-goettingen.de/pages/viewpageattachments.action?pageId=113394867&preview=/113394867/132551461/2020-11-20-emo-branches.svg

**Comment by jfrer** [comment]
In GitLab by @ghost on Aug 25, 2021, 09:45

unassigned @ghost
