### ISSUE TITLE
EMo release via npm

### ISSUE THREAD

**Issue by jfrer** [subugoe/tido#114]
In GitLab by @ghost on Nov 4, 2020, 14:38

A project needs a convenient way to integrate the Viewer

**Goals:**

- 1) publish the Viewer as npm package
- 2) install the Viewer as npm package
- 3) integrate the Viewer

**Publish**

  - [x] what to publish (build && statics && usual suspects): setup *package.json*
  - [x] setup package scope (*GitLab*)
  - [x] create access token (*GitLab*)
  - [x] configure registry setup / *.npmrc*
  - [x] configure publishing setup in *package.json*

**Install**

  - [x] setup registry according to package scope
  - [x] install the npm package

**Integrate**

  - [x] import js modules (main.js)
  - [x] import css (main.scss)
  - [x] copy config-object (project's entrypoint)

**TODOs**:

- [x] (automate) renaming of build files from checksums to readable names to ease the integration
- [x] patch / change build pipeline to end up with a single js / css file instead of 3 (if applicable)
- [x] release the Viewer as **standalone** package
- [ ] accordance on **licensing**

**Comment by jfrer** [comment]
In GitLab by @krvoigt on Nov 6, 2020, 13:51

added to epic subugoe&33

**Comment by jfrer** [comment]
In GitLab by @mathias-goebel on Nov 11, 2020, 11:17

mentioned in commit fc658b871d0eeda41850dc376918984dc7e7c0ba

**Comment by jfrer** [comment]
In GitLab by @ghost on Nov 20, 2020, 15:50

marked the checklist item **(automate) renaming of build files from checksums to readable names to ease the integration** as completed

**Comment by jfrer** [comment]
In GitLab by @ghost on Nov 27, 2020, 17:29

mentioned in commit 526fbadf331a46c930b16670a25a911c990dcf82

**Comment by jfrer** [comment]
In GitLab by @ghost on Nov 30, 2020, 16:43

marked the checklist item **patch / change build pipeline to end up with a single js / css file instead of 3 (if applicable)** as completed

**Comment by jfrer** [comment]
In GitLab by @ghost on Nov 30, 2020, 16:43

marked the checklist item **release the Viewer as **standalone** package** as completed

**Comment by jfrer** [comment]
In GitLab by @ghost on Dec 14, 2020, 10:31

mentioned in commit f752e4b16ebe5c0c776971711ec0447714405de2

**Comment by jfrer** [comment]
In GitLab by @ghost on Jan 19, 2021, 18:19

mentioned in commit 071b2762cb65e5ed3b66615726386749b543deb1

**Comment by jfrer** [comment]
In GitLab by @mweidling on Jan 25, 2021, 09:40

I think this is done. I'll close it for now @ghost .
