### ISSUE TITLE
Implement metadata according to the generic TextAPI

### ISSUE THREAD

**Issue by jfrer** [subugoe/tido#147]
In GitLab by @krvoigt on Feb 2, 2021, 21:39

**Goal**: a reference implementation according to the specs given in the generic TextAPI

Pls refer to: [generic TextAPI](https://subugoe.pages.gwdg.de/emo/text-api/page/specs/)

**TODO**:

- [x] remove rendering for x-prefix (project-specific API eXtensions)
- [x] render metadata object provided by the manifest object holding arbitrary, project specific data
- [x] keep item-sections from being rendered if no data is delivered => (cardinality "?" / "*")
- [ ] adjust the (global) config options
- [x] update the README accordingly

**Decisions** to be made:
- should everything be rendered with a cardinality of either "1" and / or "+" (if not, what should be rendered?)
- which metadata fields should be configurable (imho everything with cardiality "1" and / or "+" as far as it is about to being rendered)
- in which order should we display the single fields

**Related**:

- [Provide license information for images](https://gitlab.gwdg.de/subugoe/emo/Qviewer/-/issues/132)
- [Provide license information for the text](https://gitlab.gwdg.de/subugoe/emo/Qviewer/-/issues/133)
- [Move x- prefixed info to Metadata Object in back end](https://gitlab.gwdg.de/subugoe/ahiqar/backend/-/issues/108)

**Comment by jfrer** [comment]
In GitLab by @krvoigt on Feb 2, 2021, 21:39

added to epic subugoe&12

**Comment by jfrer** [comment]
In GitLab by @ghost on Feb 4, 2021, 11:41

@krvoigt I already left you a pm in Rocket.Chat. Let's pls discuss these topics described aboved (e.g. decisions) as soon as it fits for you :-)

**Comment by jfrer** [comment]
In GitLab by @ghost on Feb 22, 2021, 17:11

marked the checklist item **update the README accordingly** as completed

**Comment by jfrer** [comment]
In GitLab by @ghost on Feb 22, 2021, 17:11

marked the checklist item **keep item-sections from being rendered if no data is delivered => (cardinality "?" / "*")** as completed

**Comment by jfrer** [comment]
In GitLab by @ghost on Feb 23, 2021, 16:51

mentioned in commit f90322a9638aef34d9b73aaa7e335c392558a9cd
